import { ProfileData } from '@/components/profile-form'

export const SAMPLE_TECH_PROFILES: ProfileData[] = [
  {
    name: 'Alex Chen',
    title: 'Senior Software Engineer',
    major: 'Computer Science',
    yearsExperience: 12,
    skills: ['Python', 'Typescript', 'System Design', 'Machine Learning', 'AWS', 'Docker', 'React', 'Leadership'],
    companies: ['Google', 'Meta'],
    description: 'Specialized in distributed systems and ML platforms. Led teams of 5+ engineers.',
  },
  {
    name: 'Jordan Rodriguez',
    title: 'Staff Engineer',
    major: 'Computer Science',
    yearsExperience: 15,
    skills: ['Go', 'C++', 'Database Architecture', 'Kubernetes', 'Microservices', 'Mentoring', 'Technical Strategy'],
    companies: ['Amazon', 'Netflix'],
    description: 'Infrastructure expert with experience building payment systems at scale.',
  },
  {
    name: 'Sarah Kim',
    title: 'Engineering Manager',
    major: 'Computer Science',
    yearsExperience: 10,
    skills: ['Team Leadership', 'Strategic Planning', 'Typescript', 'Node.js', 'Project Management', 'Hiring'],
    companies: ['Microsoft', 'Apple'],
    description: 'Transitioned from IC to management, leading teams of 12+ engineers.',
  },
  {
    name: 'Marcus Johnson',
    title: 'Mid-Level Software Engineer',
    major: 'Software Engineering',
    yearsExperience: 5,
    skills: ['Java', 'Kotlin', 'Spring Boot', 'SQL', 'REST APIs', 'Android Development', 'Git'],
    companies: ['Uber', 'Stripe'],
    description: 'Full-stack developer with mobile and backend experience.',
  },
  {
    name: 'Emma Zhang',
    title: 'Junior Software Engineer',
    major: 'Computer Science',
    yearsExperience: 2,
    skills: ['Python', 'Javascript', 'React', 'SQL', 'Git', 'Testing', 'Agile'],
    companies: ['Slack'],
    description: 'Recent graduate growing skills across full-stack development.',
  },
  {
    name: 'David Park',
    title: 'Principal Engineer',
    major: 'Electrical Engineering',
    yearsExperience: 18,
    skills: ['System Architecture', 'Rust', 'Performance Optimization', 'Leadership', 'Technical Vision', 'AI/ML'],
    companies: ['Tesla', 'Apple'],
    description: 'Expert in performance-critical systems and company technical vision.',
  },
  {
    name: 'Lisa Martinez',
    title: 'Machine Learning Engineer',
    major: 'Computer Science',
    yearsExperience: 7,
    skills: ['Python', 'TensorFlow', 'PyTorch', 'Statistics', 'SQL', 'AWS', 'Data Analysis'],
    companies: ['Google', 'Meta'],
    description: 'Specialized in recommendation systems and NLP.',
  },
  {
    name: 'Robert Chen',
    title: 'VP Engineering',
    major: 'Computer Science',
    yearsExperience: 20,
    skills: ['Technical Leadership', 'Strategic Vision', 'Team Building', 'Architecture', 'Fundraising', 'Mentoring'],
    companies: ['Airbnb', 'Coursera'],
    description: 'Built engineering organizations from scratch. Mentors multiple leaders.',
  },
  {
    name: 'Priya Sharma',
    title: 'Software Engineer',
    major: 'Computer Science',
    yearsExperience: 4,
    skills: ['Typescript', 'Node.js', 'React', 'PostgreSQL', 'Microservices', 'Docker', 'AWS'],
    companies: ['Notion'],
    description: 'Full-stack engineer working on core platform.',
  },
  {
    name: 'James Wilson',
    title: 'Senior Software Engineer',
    major: 'Software Engineering',
    yearsExperience: 11,
    skills: ['C#', '.NET', 'Azure', 'System Design', 'Leadership', 'Mentoring', 'Agile'],
    companies: ['Microsoft', 'Adobe'],
    description: 'Enterprise software specialist with team leadership experience.',
  },
]

export const SAMPLE_DATA_SCIENCE_PROFILES: ProfileData[] = [
  {
    name: 'Michael Thompson',
    title: 'Senior Data Scientist',
    major: 'Data Science',
    yearsExperience: 10,
    skills: ['Python', 'Statistics', 'Machine Learning', 'SQL', 'R', 'Tableau', 'Communication'],
    companies: ['Netflix', 'Amazon'],
    description: 'Led data science initiatives for recommendation systems.',
  },
  {
    name: 'Dr. Elena Vasquez',
    title: 'Principal Data Scientist',
    major: 'Statistics',
    yearsExperience: 14,
    skills: ['Advanced Statistics', 'Causal Inference', 'Experimental Design', 'Python', 'Research', 'Leadership'],
    companies: ['Google', 'Meta'],
    description: 'PhD in Statistics. Expert in experimental design and causal analysis.',
  },
  {
    name: 'Amit Patel',
    title: 'Data Analyst',
    major: 'Business Administration',
    yearsExperience: 3,
    skills: ['SQL', 'Python', 'Tableau', 'Excel', 'Statistics', 'Business Analytics', 'Communication'],
    companies: ['Spotify'],
    description: 'Transitioning from business to data science.',
  },
  {
    name: 'Sophie Martin',
    title: 'ML Ops Engineer',
    major: 'Computer Science',
    yearsExperience: 6,
    skills: ['Python', 'MLflow', 'Kubernetes', 'AWS', 'Monitoring', 'CI/CD', 'Docker'],
    companies: ['Uber', 'Lyft'],
    description: 'Specialized in ML infrastructure and productionization.',
  },
  {
    name: 'Raj Kumar',
    title: 'Analytics Manager',
    major: 'Data Science',
    yearsExperience: 9,
    skills: ['SQL', 'Python', 'R', 'Team Leadership', 'Strategic Thinking', 'Tableau', 'Statistics'],
    companies: ['LinkedIn', 'Databricks'],
    description: 'Manages team of 6 data scientists. Strong business acumen.',
  },
  {
    name: 'Catherine Lee',
    title: 'Junior Data Analyst',
    major: 'Mathematics',
    yearsExperience: 1,
    skills: ['SQL', 'Python', 'Excel', 'Basic Statistics', 'Tableau', 'R'],
    companies: ['Shopify'],
    description: 'Recent hire growing analytical skills.',
  },
  {
    name: 'Vikram Singh',
    title: 'Lead Data Scientist',
    major: 'Data Science',
    yearsExperience: 8,
    skills: ['Python', 'Machine Learning', 'Deep Learning', 'Statistics', 'SQL', 'Leadership', 'Communication'],
    companies: ['Microsoft', 'Twitter'],
    description: 'Led multiple high-impact ML projects.',
  },
  {
    name: 'Julia Rodriguez',
    title: 'Research Scientist',
    major: 'Statistics',
    yearsExperience: 7,
    skills: ['Advanced Statistics', 'Python', 'R', 'Research Design', 'Academic Publishing', 'Machine Learning'],
    companies: ['DeepMind', 'OpenAI'],
    description: 'PhD. Focused on research and innovation.',
  },
]

export const SAMPLE_PRODUCT_PROFILES: ProfileData[] = [
  {
    name: 'David Park',
    title: 'VP Product',
    major: 'Business Administration',
    yearsExperience: 13,
    skills: ['Product Strategy', 'Leadership', 'Analytics', 'User Research', 'Roadmapping', 'Cross-functional Collaboration'],
    companies: ['Slack', 'Dropbox'],
    description: 'Built product orgs at scale. Expert in product-market fit.',
  },
  {
    name: 'Lisa Chen',
    title: 'Senior Product Manager',
    major: 'Economics',
    yearsExperience: 8,
    skills: ['Product Management', 'Data Analysis', 'User Research', 'Roadmapping', 'Prioritization', 'Leadership'],
    companies: ['Airbnb', 'Stripe'],
    description: 'Managed $500M revenue product line.',
  },
  {
    name: 'Thomas Brown',
    title: 'Product Manager',
    major: 'Business Administration',
    yearsExperience: 4,
    skills: ['Product Thinking', 'Analytics', 'SQL', 'Roadmapping', 'User Research', 'Documentation'],
    companies: ['Twitter', 'Square'],
    description: 'Growing skills in analytics and user research.',
  },
  {
    name: 'Ananya Gupta',
    title: 'Director of Product',
    major: 'Product Management',
    yearsExperience: 11,
    skills: ['Product Leadership', 'Strategy', 'Team Management', 'Analytics', 'Hiring', 'Mentoring'],
    companies: ['Google', 'Meta'],
    description: 'Built multiple product teams. Strong mentor.',
  },
  {
    name: 'Marcus Lee',
    title: 'Associate Product Manager',
    major: 'Business Administration',
    yearsExperience: 1,
    skills: ['Product Analysis', 'Writing', 'Analytics', 'User Research', 'Roadmapping', 'Cross-functional Collaboration'],
    companies: ['Notion'],
    description: 'Recent MBA graduate launching PM career.',
  },
]

export const SAMPLE_PROFILES_BY_FIELD: { [key: string]: ProfileData[] } = {
  'Computer Science': SAMPLE_TECH_PROFILES,
  'Software Engineering': SAMPLE_TECH_PROFILES,
  'Data Science': SAMPLE_DATA_SCIENCE_PROFILES,
  'Product Management': SAMPLE_PRODUCT_PROFILES,
  'Engineering': SAMPLE_TECH_PROFILES,
  'Business Administration': SAMPLE_PRODUCT_PROFILES,
  'Economics': SAMPLE_PRODUCT_PROFILES,
}

export function getSampleProfiles(major: string): ProfileData[] {
  return SAMPLE_PROFILES_BY_FIELD[major] || SAMPLE_TECH_PROFILES
}
